- name: "repo-install"
  yum: name=https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm

- name: "agent-install"
  yum: name=zabbix-agent

- name: "agentd.conf copy"
  template: src=roles/zabbix/template/zabbix_agentd.j2 dest=/etc/zabbix/zabbix_agentd.conf backup=yes

- name: "agent-start"
  service: name="zabbix-agent" state=restarted enabled=yes
